Repository cloudposse/terraform-aws-alb, pull requests merged in 2024-11, with the labels that each got.

#187 feat: redirect default action for https listener
  README.md
  docs/terraform.md
  main.tf
  test/src/examples_complete_test.go
  variables.tf
Labels: triage

#186 Add IPv6 ingress security group rules
  README.md
  docs/terraform.md
  main.tf
  variables.tf
Labels: minor, feature

#189 feat: alb client keep alive
  README.md
  docs/terraform.md
  main.tf
  variables.tf
  versions.tf
Labels: major, triage

#190 fix: listener default action variable object block [HOTFIX REQUIRED!]
  README.md
  docs/terraform.md
  variables.tf
Labels: triage
